# Background and foreground colors
background = #181f1c
foreground = #f3f3f3

# Standard colors
palette = 0=#181f1c
palette = 1=#8f9995
palette = 2=#8a9590
palette = 3=#9aa39f
palette = 4=#aab2ae
palette = 5=#bac0be
palette = 6=#cacfcd
palette = 7=#e7e5e7

# Bright colors
palette = 8=#cbcecd
palette = 9=#bfc5c3
palette = 10=#a5adaa
palette = 11=#b4bcb9
palette = 12=#c5cac8
palette = 13=#d4d9d7
palette = 14=#e5e7e6
palette = 15=#f3f3f3
