background            #181f1c
foreground            #f3f3f3

# black
color0  #181f1c
color8  #cbcecd

# red
color1  #8f9995
color9  #bfc5c3

# green
color2  #8a9590
color10 #a5adaa

# yellow
color3  #9aa39f
color11 #b4bcb9

# blue
color4  #aab2ae
color12 #c5cac8

# magenta
color5  #bac0be
color13 #d4d9d7

#cyan
color6  #cacfcd
color14 #e5e7e6

#white
color7  #e7e5e7
color15 #f3f3f3


